name: Apply Branch Protection

on:
  workflow_dispatch:

jobs:
  apply-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run protection script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python apply_protection.py
