name: Apply Branch Protection

on:
  workflow_dispatch:

jobs:
  apply-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Apply branch protection
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python -c 'import os, requests
h = {"Authorization": f"token {os.environ[\"GH_TOKEN\"]}", "Accept": "application/vnd.github.v3+json"}
url = "https://api.github.com/repos/Jyosna123/Project/branches/master/protection"
payload = {
  "required_pull_request_reviews": {"dismiss_stale_reviews": True},
  "enforce_admins": False,
  "restrictions": None,
  "required_status_checks": None
}
res = requests.put(url, headers=h, json=payload)
print(res.status_code, res.text)'
