name: Apply Branch Protection

on:
  workflow_dispatch:

jobs:
  apply-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Apply branch protection
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Running branch protection script..."
          python - <<EOF
import os
import requests

token = os.environ.get("GH_TOKEN")
if not token:
    raise Exception("GH_TOKEN is not set")

headers = {
    "Authorization": "token " + token,
    "Accept": "application/vnd.github.v3+json"
}

url = "https://api.github.com/repos/Jyosna123/Project/branches/master/protection"

payload = {
    "required_pull_request_reviews": {"dismiss_stale_reviews": True},
    "enforce_admins": False,
    "restrictions": None,
    "required_status_checks": None
}

res = requests.put(url, headers=headers, json=payload)
print("Status:", res.status_code)
print("Response:", res.text)
EOF
