        run: |
          echo "import os
import requests
import json

token = os.environ.get('GH_TOKEN')
if not token:
    print('Error: GH_TOKEN is not set')
    exit(1)

headers = {
    'Authorization': f'token {token}',
    'Accept': 'application/vnd.github.v3+json'
}

url = 'https://api.github.com/repos/Jyosna123/Project/branches/main/protection'

payload = {
    'required_pull_request_reviews': {
        'dismiss_stale_reviews': True
    },
    'enforce_admins': False,
    'restrictions': None,
    'required_status_checks': None
}

res = requests.put(url, headers=headers, json=payload)

print('Status:', res.status_code)
try:
    print('Response:', res.json())
except Exception as e:
    print('Failed to parse JSON response:', res.text)
    print('Error:', str(e))
" > script.py
          python script.py
